// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFzTeb6x7qkCgrjAnG8gM2gkAM6BerA0',
    appId: '1:641919532779:web:6c5e85401719f6c30cc8ae',
    messagingSenderId: '641919532779',
    projectId: 'expense-tracker-d623f',
    authDomain: 'expense-tracker-d623f.firebaseapp.com',
    storageBucket: 'expense-tracker-d623f.firebasestorage.app',
    measurementId: 'G-VMT3DPGXLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYSPR_BCM02GjTpmk2iini-S8sp0QAlU',
    appId: '1:641919532779:android:8484f169f06d68050cc8ae',
    messagingSenderId: '641919532779',
    projectId: 'expense-tracker-d623f',
    storageBucket: 'expense-tracker-d623f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRv7Lsl3tJWLFRM-fJFcniEXX19lFfzQ',
    appId: '1:641919532779:ios:de455129078680ac0cc8ae',
    messagingSenderId: '641919532779',
    projectId: 'expense-tracker-d623f',
    storageBucket: 'expense-tracker-d623f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRv7Lsl3tJWLFRM-fJFcniEXX19lFfzQ',
    appId: '1:641919532779:ios:de455129078680ac0cc8ae',
    messagingSenderId: '641919532779',
    projectId: 'expense-tracker-d623f',
    storageBucket: 'expense-tracker-d623f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPFzTeb6x7qkCgrjAnG8gM2gkAM6BerA0',
    appId: '1:641919532779:web:dfbbe2f205ab2c9a0cc8ae',
    messagingSenderId: '641919532779',
    projectId: 'expense-tracker-d623f',
    authDomain: 'expense-tracker-d623f.firebaseapp.com',
    storageBucket: 'expense-tracker-d623f.firebasestorage.app',
    measurementId: 'G-B6PMJ3QNKQ',
  );
}
